export const specializations = [
  'Anxiety',
  'Depression',
  'Stress Management',
  'Trauma',
  'PTSD',
  'Grief',
  'Relationships',
  'Family Conflict',
  'Self-esteem',
  'Addiction',
  'Life Transitions',
  'Burnout',
  'Work-related Stress',
  'Childhood Trauma',
  'Communication',
  'Couples Therapy',
  'Loss',
  'OCD',
  'Phobias',
  'Parenting',
  'ADHD',
  'Self-regulation',
  'Productivity',
  'Cultural Identity',
  'Recovery Support',
  'Codependency',
  'Eating Disorders',
  'Body Image',
  "Men's Mental Health",
  'Expat Mental Health',
  'Complex Trauma',
  'Self-discovery',
  'Social Anxiety',
] as const;

export const approaches = [
  'Anxiety',
  'Depression',
  'Stress Management',
  'Trauma',
  'PTSD',
  'Grief',
  'Relationships',
  'Family Conflict',
  'Self-esteem',
  'Addiction',
  'Life Transitions',
  'Burnout',
  'Work-related Stress',
  'Childhood Trauma',
  'Communication',
  'Couples Therapy',
  'Loss',
  'OCD',
  'Phobias',
  'Parenting',
  'ADHD',
  'Self-regulation',
  'Productivity',
  'Cultural Identity',
  'Recovery Support',
  'Codependency',
  'Eating Disorders',
  'Body Image',
  "Men's Mental Health",
  'Expat Mental Health',
  'Complex Trauma',
  'Self-discovery',
  'Social Anxiety',
] as const;

export type Specialization = (typeof specializations)[number];
export type Approach = (typeof approaches)[number];
