import type { Metadata } from 'next';
import { Geist, Manrope } from 'next/font/google';
import './globals.css';
import 'modern-normalize/modern-normalize.css';
import Header from '@/components/Header/Header';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${manrope.variable}`}>
      <body>
        <header>
          <Header />
        </header>
        <main>{children}</main>
        <footer></footer>
        {modal}
      </body>
    </html>
  );
}
